[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements_railway.txt"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "mkdir -p input downloads text logs output",
    "python -c 'import nltk; nltk.download(\"punkt\", quiet=True); nltk.download(\"stopwords\", quiet=True)'"
]

[start]
cmd = "python railway_web_app.py"