services:
  - type: web
    name: comment-analyzer
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 8080
    disk:
      name: comment-analyzer-data
      mountPath: /app/data
      sizeGB: 1